#!/bin/bash

# CPU CORE
VOLTS_CORE=$(vcgencmd measure_volts core | cut -d '=' -f 2)
# SDRAM Controller
VOLTS_SDRAM_C=$(vcgencmd measure_volts sdram_c | cut -d '=' -f 2)
# SDRAM I/O
VOLTS_SDRAM_I=$(vcgencmd measure_volts sdram_i | cut -d '=' -f 2)
# SDRAM Physical memory
VOLTS_SDRAM_P=$(vcgencmd measure_volts sdram_p | cut -d '=' -f 2)

TEMP=$(vcgencmd measure_temp | cut -d '=' -f 2)
FREQ=$(vcgencmd get_config arm_freq | cut -d '=' -f 2)

echo TEMP: $TEMP
echo FREQ: $FREQ
echo CORE: $VOLTS_CORE
echo SDRAM CTRL: $VOLTS_SDRAM_C
echo SDRAM I/O: $VOLTS_SDRAM_I
echo SDRAM MEM: $VOLTS_SDRAM_P
